# Generated by Django 5.2.14 on 2026-05-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_status', models.CharField(choices=[('PASSING', 'Passing'), ('FAILING', 'Failing'), ('NO_STATUS', 'No Status')], default='NO_STATUS', max_length=10)),
                ('devEUI', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fCnt', models.IntegerField()),
                ('data', models.TextField()),
                ('status', models.CharField(choices=[('PASSING', 'Passing'), ('FAILING', 'Failing'), ('NO_STATUS', 'No Status')], default='NO_STATUS', max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexmodal.device', to_field='devEUI')),
            ],
        ),
    ]
